version: '3.8'
services:
  mysql:
    image: mysql
    container_name: my-mysql-8-rasmo
#    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: DBRAS
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - '3306:3306'
    volumes:
      - mysql_data_container:/data/db

#  redis:
#    image: redis:4
#    container_name: redis-rasplus
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis_data_container:/data/redis
volumes:
  mysql_data_container:
  redis_data_container: